name: Build Frontend

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Publish Blazor WASM
        run: |
          dotnet publish HundredDays.csproj -c Release -o publish

      - name: Fix Blazor runtime filenames
        run: |
          cd publish/wwwroot/_framework

          DOTNET_FILE=$(ls dotnet.*.js | grep -v 'dotnet.js' | head -n 1 | sed 's/\.js//')

          cp "$DOTNET_FILE.js" dotnet.js
          cp "$DOTNET_FILE.js.br" dotnet.js.br || true
          cp "$DOTNET_FILE.js.gz" dotnet.js.gz || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hundreddays-frontend
          path: publish/wwwroot
