- name: Publish Blazor WASM
  run: |
    dotnet publish HundredDays.csproj -c Release -o publish

- name: Upload artifact
  uses: actions/upload-artifact@v4
  with:
    name: hundreddays-frontend
    path: publish/wwwroot
